-- Query Script to Display Sample Data
-- This script shows the data in all created tables

-- Connect to the pluggable database
ALTER SESSION SET CONTAINER = XEPDB1;

-- Set formatting for better display
SET LINESIZE 120;
SET PAGESIZE 50;

-- Display Client Types
SELECT 'CLIENT TYPES' AS "TABLE SECTION" FROM DUAL;
SELECT CLIENT_TYPE, TYPE_NAME, DISCOUNT_RATE, REMARKS FROM Client_Type ORDER BY CLIENT_TYPE;

-- Display Clients
SELECT 'CLIENTS' AS "TABLE SECTION" FROM DUAL;
SELECT CLIENT_NO, CLIENTNAME, CITY, PHONE, CLIENT_TYPE, DISCOUNT FROM Clients ORDER BY CLIENT_NO;

-- Display Product Types
SELECT 'PRODUCT TYPES' AS "TABLE SECTION" FROM DUAL;
SELECT PRODUCTTYPE_ID, PRODUCTTYPE_NAME, REMARKS FROM Product_Type ORDER BY PRODUCTTYPE_ID;

-- Display Products
SELECT 'PRODUCTS' AS "TABLE SECTION" FROM DUAL;
SELECT PRODUCT_NO, PRODUCTNAME, PRODUCTTYPE, SELL_PRICE, COST_PRICE, QTY_ON_HAND FROM Products ORDER BY PRODUCT_NO;

-- Display Jobs
SELECT 'JOBS' AS "TABLE SECTION" FROM DUAL;
SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY FROM JOBS ORDER BY JOB_ID;

-- Display Employees
SELECT 'EMPLOYEES' AS "TABLE SECTION" FROM DUAL;
SELECT EMPLOYEEID, EMPLOYEENAME, GENDER, JOB_ID, SALARY FROM Employees ORDER BY EMPLOYEEID;

-- Display Invoices
SELECT 'INVOICES' AS "TABLE SECTION" FROM DUAL;
SELECT INVOICENO, INVOICE_DATE, CLIENT_NO, EMPLOYEEID, INVOICE_STATUS FROM INVOICES ORDER BY INVOICENO;

-- Display Invoice Details
SELECT 'INVOICE DETAILS' AS "TABLE SECTION" FROM DUAL;
SELECT INVOICENO, PRODUCT_NO, QTY, PRICE FROM INVOICE_DETAILS ORDER BY INVOICENO, PRODUCT_NO;

-- Display a joined query showing invoice summary
SELECT 'INVOICE SUMMARY WITH CUSTOMER NAMES' AS "TABLE SECTION" FROM DUAL;
SELECT 
    i.INVOICENO,
    c.CLIENTNAME,
    e.EMPLOYEENAME as SALESPERSON,
    i.INVOICE_DATE,
    i.INVOICE_STATUS,
    SUM(id.QTY * id.PRICE) as TOTAL_AMOUNT
FROM INVOICES i
JOIN Clients c ON i.CLIENT_NO = c.CLIENT_NO
JOIN Employees e ON i.EMPLOYEEID = e.EMPLOYEEID
JOIN INVOICE_DETAILS id ON i.INVOICENO = id.INVOICENO
GROUP BY i.INVOICENO, c.CLIENTNAME, e.EMPLOYEENAME, i.INVOICE_DATE, i.INVOICE_STATUS
ORDER BY i.INVOICENO;

EXIT;