services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe-db
    restart: unless-stopped
    ports:
      - "1522:1521"
      - "5501:5500"  # Oracle Enterprise Manager Express
    environment:
      - ORACLE_PWD=${ORACLE_PWD:-Oracle123}
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-scripts:/docker-entrypoint-initdb.d/startup
      - ./init-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/$$ORACLE_PWD@//localhost:1521/XE", "@/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  oracle-data:
    driver: local