# Minimal docker-compose for Oracle DB and PHP web app
version: '3.8'
services:
  # Oracle XE database container
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe-db
    ports:
      - "1522:1521" # Oracle DB port
    environment:
      - ORACLE_PWD=Oracle123 # Set your Oracle password
    volumes:
      - oracle-data:/opt/oracle/oradata # Persist database data
      - ./init-scripts:/docker-entrypoint-initdb.d/startup # Init scripts
    networks:
      - oracle-network

  # PHP web application container
  web-app:
    build: ./web-app
    container_name: php-web-app
    ports:
      - "8090:80" # Expose web app on host port 8090
    depends_on:
      - oracle-db # Ensure DB starts first
    volumes:
      - ./web-app/public:/var/www/html
      - ./web-app/config:/var/www/html/config
      - ./web-app/includes:/var/www/html/includes
      - ./web-app/assets:/var/www/html/assets
    networks:
      - oracle-network

volumes:
  oracle-data:

networks:
  oracle-network: