SELECT ID, TYPE_NAME FROM CLIENT_TYPE ORDER BY ID;

SELECT ID, TYPE_NAME FROM PRODUCT_TYPE ORDER BY ID;

SELECT COUNT(*) as CLIENT_COUNT FROM CLIENTS;

SELECT COUNT(*) as PRODUCT_COUNT FROM PRODUCTS;

EXIT;